import type { ProviderConfig } from "@/providers/types";

export const KDMHS_CONFIG: ProviderConfig = {
  id: "kdmhs",
  name: "한국디지털미디어고등학교",
  basePath: "/kdmhs",
  dbName: "bap",
  collection: "meal_data",
  presentation: {
    id: "kdmhs",
    name: "디미고 급식",
    schoolName: "한국디지털미디어고등학교",
    basePath: "/kdmhs",
    description: "디미고 급식을 확인해보세요",
    keywords: ["급식", "디미고", "한국디지털미디어고등학교", "식단", "밥.net"],
    googleSiteVerification: "Autqjgf5q34Q-Bi4JnRwIuiJW-WzwkCU6Y4wlGU0IVU",
    adsenseClient: "ca-pub-2186209581588169",
    features: { foodSearch: true },
    meals: [
      {
        id: "breakfast",
        title: "아침",
        operatingHours: null,
        icon: "/icon/breakfast.svg",
        background: "/img/breakfast.svg",
        activeUntilHour: 8,
      },
      {
        id: "lunch",
        title: "점심",
        operatingHours: null,
        icon: "/icon/lunch.svg",
        background: "/img/lunch.svg",
        activeUntilHour: 14,
      },
      {
        id: "dinner",
        title: "저녁",
        operatingHours: null,
        icon: "/icon/dinner.svg",
        background: "/img/dinner.svg",
        activeUntilHour: 20,
      },
    ],
  },
  schedule: [
    { day: 0, hour: 3, minute: 0, refreshType: "all" },
    { day: 0, hour: 7, minute: 0, refreshType: "today" },
    { day: 0, hour: 9, minute: 0, refreshType: "today" },
    { day: 0, hour: 11, minute: 50, refreshType: "today" },
    { day: 0, hour: 15, minute: 0, refreshType: "today" },
    { day: 0, hour: 17, minute: 50, refreshType: "today" },
    { day: 0, hour: 21, minute: 0, refreshType: "today" },
    { day: 1, hour: 3, minute: 0, refreshType: "all" },
    { day: 1, hour: 6, minute: 30, refreshType: "today" },
    { day: 1, hour: 9, minute: 0, refreshType: "today" },
    { day: 1, hour: 12, minute: 40, refreshType: "today" },
    { day: 1, hour: 15, minute: 0, refreshType: "today" },
    { day: 1, hour: 18, minute: 20, refreshType: "today" },
    { day: 1, hour: 21, minute: 0, refreshType: "today" },
    { day: 2, hour: 3, minute: 0, refreshType: "all" },
    { day: 2, hour: 6, minute: 30, refreshType: "today" },
    { day: 2, hour: 9, minute: 0, refreshType: "today" },
    { day: 2, hour: 12, minute: 40, refreshType: "today" },
    { day: 2, hour: 15, minute: 0, refreshType: "today" },
    { day: 2, hour: 18, minute: 20, refreshType: "today" },
    { day: 2, hour: 21, minute: 0, refreshType: "today" },
    { day: 3, hour: 3, minute: 0, refreshType: "all" },
    { day: 3, hour: 6, minute: 30, refreshType: "today" },
    { day: 3, hour: 9, minute: 0, refreshType: "today" },
    { day: 3, hour: 12, minute: 40, refreshType: "today" },
    { day: 3, hour: 15, minute: 0, refreshType: "today" },
    { day: 3, hour: 18, minute: 20, refreshType: "today" },
    { day: 3, hour: 21, minute: 0, refreshType: "today" },
    { day: 4, hour: 3, minute: 0, refreshType: "all" },
    { day: 4, hour: 6, minute: 30, refreshType: "today" },
    { day: 4, hour: 9, minute: 0, refreshType: "today" },
    { day: 4, hour: 12, minute: 40, refreshType: "today" },
    { day: 4, hour: 15, minute: 0, refreshType: "today" },
    { day: 4, hour: 18, minute: 20, refreshType: "today" },
    { day: 4, hour: 21, minute: 0, refreshType: "today" },
    { day: 5, hour: 3, minute: 0, refreshType: "all" },
    { day: 5, hour: 6, minute: 30, refreshType: "today" },
    { day: 5, hour: 9, minute: 0, refreshType: "today" },
    { day: 5, hour: 12, minute: 40, refreshType: "today" },
    { day: 5, hour: 15, minute: 0, refreshType: "today" },
    { day: 5, hour: 18, minute: 20, refreshType: "today" },
    { day: 5, hour: 21, minute: 0, refreshType: "today" },
    { day: 6, hour: 3, minute: 0, refreshType: "all" },
    { day: 6, hour: 7, minute: 0, refreshType: "today" },
    { day: 6, hour: 9, minute: 0, refreshType: "today" },
    { day: 6, hour: 11, minute: 50, refreshType: "today" },
    { day: 6, hour: 15, minute: 0, refreshType: "today" },
    { day: 6, hour: 17, minute: 50, refreshType: "today" },
    { day: 6, hour: 21, minute: 0, refreshType: "today" },
  ],
};

export const KDMHS_WEBSITE = {
  BASE_URL: "https://dimigo-h.goeas.kr",
  TABLE_PATH: "dimigo-h/ad/fm/foodmenu/selectFoodMenuView.do",
} as const;

export const MEAL_TYPES = {
  BREAKFAST: "조식",
  LUNCH: "중식",
  DINNER: "석식",
} as const;
