name: CI/CD Docker

on:
  push:
    branches: [ main ]

env:
  DOCKER_IMAGE: ghcr.io/${{ github.repository }}
  VERSION: ${{ github.sha }}
  NAME: ${{ github.repository_id }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ env.VERSION }}
          restore-keys: ${{ runner.os }}-buildx-
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and Push Docker Image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

  deploy:
    needs: build
    name: Deploy
    runs-on: [ self-hosted, label-go ]
    env:
      DOCKER_IMAGE: ghcr.io/${{ github.repository }}
      NAME: ${{ github.repository_id }}
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Docker Run
        env:
          CONTAINER_NAME: ${{ env.NAME }}
          IMAGE: ${{ env.DOCKER_IMAGE }}:latest
          SCRAPELESS_KEY: ${{ secrets.SCRAPELESS_API_KEY }}
          MONGO_URI: ${{ secrets.MONGODB_URI }}
          MONGO_DB: ${{ secrets.MONGODB_DB_NAME }}
        run: |
          docker stop "${CONTAINER_NAME}" || true
          docker rm "${CONTAINER_NAME}" || true
          docker rmi "${IMAGE}" || true
          docker run -d \
            -p 3002:3000 \
            --name "${CONTAINER_NAME}" \
            --restart always \
            -e SCRAPELESS_API_KEY="${SCRAPELESS_KEY}" \
            -e MONGODB_URI="${MONGO_URI}" \
            -e MONGODB_DB_NAME="${MONGO_DB}" \
            "${IMAGE}"